modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/SirPuli/"
[[mods]]
modId="powergems"
version="0.1"
displayName="Power Gems"
displayURL="https://github.com/SirPuli/"
authors="SirPuli"
description='''
Gems of Power
'''

[[dependencies.powergems]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powergems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
